version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  ping-exporter:
    build: ./ping-exporter
    ports:
      - "8085:8085"
    volumes:
      - ./ping-exporter/ping-exporter.py:/ping-exporter.py
    command: python /ping-exporter.py
